# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_reversed', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='usd', max_length=25)),
                ('destination', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('metadata', jsonfield.fields.JSONField(blank=True, null=True)),
                ('source_type', models.TextField(blank=True, null=True)),
                ('statement_descriptor', models.TextField(blank=True, null=True)),
                ('transfer_group', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=25)),
                ('type', models.TextField(blank=True, null=True)),
                ('failure_code', models.TextField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='pinax_stripe.Event')),
                ('stripe_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='failure_code',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='failure_message',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='method',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='type',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='pinax_stripe.Event'),
        ),
    ]
